### ISSUE TITLE
Prepositions in HebrewStrong.xml

### ISSUE THREAD

**Issue by jfreeman88** [openscriptures/HebrewLexicon#9]
Strong's numbers are of the form "**3417**".  In _HebrewStrong.xml_, these identifiers are modified to "**H3417**".  

Exceptionally, prepositions are of the form "**b**", "**d**", "**l**", etc.  I have looked, but I cannot find these identifiers in the XML file.  I am looking for "**Hb**", "**Hd**", and "**Hl**", but I don't know if they were ever added.

I am grateful for the help in advance.

P.S. This is a wonderful project!

**Comment by DavidTroidl** [comment]
"b", "d", "l", etc. represent prefixes on the Hebrew words, some of which are prepositional. They are not defined in Strong's dictionary. They are mapped by AugIndex.xml into the Lexical Index, and carried over from there to their definitions in Brown, Driver, Briggs.

**Comment by jfreeman88** [comment]
I submitted a pull request, but I understand now that the prefixes in the `xref` are intentional. Closing.
